# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4d72de9045990667bef7a3d1415a99a6b38ae2a66f1ad686f4ddd5344abfa3b719874a8afa6b5ef39cbacf964a77a563f146e7f5f26c64c156afe7dfdca51d3
  paypal_host: https://www.sandbox.paypal.com
  app_host:    http://maaaapkichaaya.herokuapp.com/


test:
  secret_key_base: 05eac51a0fdc1f66dceeb08810069f4397def7c39bb4664ed87ce92dae686959f39c22cd78f70c5122e5e58113f4c70b7088107abfb9f33677360f2882a9c812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 34191a5432e1c96641280a2dba303d55b766544d223c0c9c9cc5a4902f42251bc9fad638736423a3b18f71414198438b7cd843fa245f5bd09bbc96565d27c40b
  paypal_host: https://www.sandbox.paypal.com
#  app_host: http://maaaapkichaaya.herokuapp.com/
